### ISSUE TITLE
Setup Project Management (BaseCamp)

### ISSUE THREAD

**Issue by hammadj** [raid-guild/HQ#2]
- What are the active projects?
- Who is working on it, if anyone?
- Whats the status of the project?
- Who are the clients?
- What is their budget?
- What tools will we use?
- Sourcecred on github?
- https://linear.app
- How can we gamify closing issues and PRs?
- Team chat? Slack / discord?
- Formalized Design Sprint Process

**Comment by hammadj** [comment]
@ahoff-axiom To setup basecamp

**Comment by ahoff-axiom** [comment]
Complete:
https://3.basecamp.com

Raid bosses should be responsible for adding their raids under the "projects" section. I think we can self organize into "teams" and HQ is for everyone
